name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        
    - name: Install Python dependencies
      run: |
        pip3 install buildozer cython
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ltrconverter-apk
        path: bin/*.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        tag_name: v${{ github.run_number }}
        name: LTR Converter Bot APK v${{ github.run_number }}
        body: |
          🤖 LTR Converter Bot Android APK
          
          **Build Information:**
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Build Number: ${{ github.run_number }}
          
          **Installation:**
          1. Download the APK file
          2. Transfer to your Android device
          3. Enable "Install from unknown sources"
          4. Install the APK
          5. Configure bot settings in the app
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
